apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    jenkins.io/github-folder: folder-name/project-name
    # backstage.io/techdocs-ref: url:https://github.com/backstage/backstage
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
